// Originally generated by Amplify Shader Editor as a surface shader.
// Hand-ported to an explicit vertex/fragment pass so it renders under URP:
// surface shaders (#pragma surface) are a Built-in RP feature and are skipped
// entirely by the Universal Render Pipeline, which made every material using
// this shader invisible.
//
// The port is behaviour-preserving. The original declared a custom lighting
// model `LightingUnlit` that returned half4(0,0,0,s.Alpha) -- it contributed
// no light whatsoever -- and wrote all visible colour through o.Emission.
// The fragment maths below is the original surf() body verbatim; only the
// plumbing around it changed. Property names, defaults and attributes are
// unchanged, so existing .mat files bind without edits.
//
// The original ASE node graph is preserved in git history if it is ever needed
// (the ASEMaterialInspector custom editor was already dead -- Amplify Shader
// Editor is not installed in this project).
Shader "GAP/ParticlesAdditiveMobile_Scroll"
{
	Properties
	{
		[HDR]_Color("Color", Color) = (0,0,0,0)
		[NoScaleOffset]_Mask("Mask", 2D) = "white" {}
		[NoScaleOffset]_MainTex("MainTex", 2D) = "white" {}
		_MainTexTiling("MainTexTiling", Vector) = (1,1,0,0)
		_MainTexSpeed("MainTexSpeed", Vector) = (0,0,0,0)
		_DistortionAmount("DistortionAmount", Range( -1 , 1)) = 0.1741219
		[NoScaleOffset]_DistortionTexture("DistortionTexture", 2D) = "white" {}
		_DistortionTiling("DistortionTiling", Vector) = (1,1,0,0)
		_DistortionSpeed("DistortionSpeed", Vector) = (0,0.1,0,0)
		_DissolveAmount("DissolveAmount", Float) = 2
		[NoScaleOffset]_DissolveTexture("DissolveTexture", 2D) = "white" {}
		_DissolveTiling("DissolveTiling", Vector) = (1,1,0,0)
		_DissolveSpeed("DissolveSpeed", Vector) = (0,0.1,0,0)
		[HideInInspector] _texcoord( "", 2D ) = "white" {}
		[HideInInspector] __dirty( "", Int ) = 1
	}

	SubShader
	{
		Tags { "RenderType"="Transparent" "Queue"="Transparent" "IgnoreProjector"="True" "PreviewType"="Plane" }

		Cull Off
		ZWrite Off
		ZTest LEqual
		Offset 0 , 0
		Blend One One , One One

		Pass
		{
			// Deliberately no LightMode tag: an untagged pass is drawn by both
			// URP and the Built-in RP. Tagging it ForwardBase would hide it
			// under URP, which is the bug this file was written to fix.
			CGPROGRAM
			#pragma vertex vert
			#pragma fragment frag
			#pragma target 2.0
			#pragma multi_compile_instancing
			#include "UnityCG.cginc"

			struct appdata
			{
				float4 vertex : POSITION;
				float4 color : COLOR;
				float2 uv : TEXCOORD0;
				UNITY_VERTEX_INPUT_INSTANCE_ID
			};

			struct v2f
			{
				float4 pos : SV_POSITION;
				float4 color : COLOR;
				float2 uv : TEXCOORD0;
				UNITY_VERTEX_OUTPUT_STEREO
			};

			sampler2D _Mask;
			sampler2D _MainTex;
			sampler2D _DistortionTexture;
			sampler2D _DissolveTexture;

			// Vector properties are float4 on the C# side; declaring them as
			// float4 here (and swizzling) keeps the constant-buffer layout
			// matching Unity's, which a bare float2 would silently shift.
			CBUFFER_START(UnityPerMaterial)
				float4 _Color;
				float4 _MainTexTiling;
				float4 _MainTexSpeed;
				float4 _DistortionTiling;
				float4 _DistortionSpeed;
				float4 _DissolveTiling;
				float4 _DissolveSpeed;
				float _DistortionAmount;
				float _DissolveAmount;
			CBUFFER_END

			v2f vert( appdata v )
			{
				v2f o;
				UNITY_SETUP_INSTANCE_ID( v );
				UNITY_INITIALIZE_OUTPUT( v2f, o );
				UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO( o );
				o.pos = UnityObjectToClipPos( v.vertex );
				o.color = v.color;
				o.uv = v.uv;
				return o;
			}

			float4 frag( v2f i ) : SV_Target
			{
				float2 uv_texcoord = i.uv;
				float2 uv_Mask5 = uv_texcoord;
				float2 uv_TexCoord37 = uv_texcoord * ( _MainTexTiling.xy - float2( 1,1 ) );
				float2 panner27 = ( 1.0 * _Time.y * _MainTexSpeed.xy + uv_TexCoord37);
				float2 uv_TexCoord42 = uv_texcoord * _DistortionTiling.xy;
				float2 panner25 = ( 1.0 * _Time.y * _DistortionSpeed.xy + uv_TexCoord42);
				float4 lerpResult17 = lerp( float4( uv_texcoord, 0.0 , 0.0 ) , tex2D( _DistortionTexture, panner25 ) , _DistortionAmount);
				float2 uv_TexCoord45 = uv_texcoord * _DissolveTiling.xy;
				float2 panner30 = ( 1.0 * _Time.y * _DissolveSpeed.xy + uv_TexCoord45);
				float4 temp_cast_5 = (_DissolveAmount).xxxx;
				float4 temp_output_9_0 = ( i.color * ( _Color * ( tex2D( _Mask, uv_Mask5 ) * ( tex2D( _MainTex, ( float4( panner27, 0.0 , 0.0 ) + lerpResult17 ).rg ).a * pow( tex2D( _DissolveTexture, ( lerpResult17 + float4( panner30, 0.0 , 0.0 ) ).rg ) , temp_cast_5 ) ) ) ) );
				// Original wrote o.Emission = .rgb and o.Alpha = .a; with the
				// zero-contribution lighting model that is exactly this value.
				return float4( temp_output_9_0.rgb, temp_output_9_0.a );
			}
			ENDCG
		}
	}
	Fallback Off
}
